version: "3.8"

services:
  ng:
    image: nginx:latest
    networks:
      - demonet
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 20M

 
  nextcloud:
    networks:
      - demonet
    depends_on:
      - postgresql 
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html/
    environment:
      - .env
    restart: always     

    # Configured Backends
  postgresql:
    networks:
      - demonet
    image: postgres:latest
    environment:
        - POSTGRES_DB=psdata
        - POSTGRES_USER= postgres
        - POSTGRES_HOST= nextcloud:5234
        - POSTGRES_PASSWORD= rootroot
    restart: always
    volumes:
        -  app:/var/lib/postgresql/data
        
volumes:
    app:
    nextcloud:


networks:
  demonet:
    driver: bridge
  